apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: ${{ values.repo_name }}
  title: ${{ values.environment }} GCP Infrastructure
  description: Terraform code for provisioning GCP infrastructure on Google Cloud

  annotations:
    github.com/project-slug: Backstage-IDP-PoC/${{ values.repo_name }}                       #Add your GitHub Organization's name here at Line no 10
    backstage.io/techdocs-ref: dir:.
    backstage.io/source-location: url:https://github.com/Backstage-IDP-PoC/${{ values.repo_name }}                   #Add your GitHub Organization's name here at Line no 12
    jenkins.io/job-full-name: Backstage_PoC/${{ values.repo_name }}/main                  #Add your Jenkins Organization's Name here Line no. 13

  tags:
    - gcp
    - compute
    - storage
    - networking
    - terraform
    

  links:
    - url: https://console.cloud.google.com/storage/browser/${{ values.environment }}-${{ values.bucket_name }}
      title: GCP Storage Bucket
      icon: cloud

    - url: https://console.cloud.google.com/compute/instances
      title: Compute Engine Instances (VMs)
      icon: dashboard

    - url: https://console.cloud.google.com/networking/networks/list
      title: VPC Networks
      icon: dashboard

    - url: https://github.com/Backstage-IDP-PoC/${{ values.repo_name }}                  #Add your GitHub Organization's name here at Line no 36
      title: GitHub Repository
      icon: github

spec:
  type: infrastructure
  lifecycle: experimental
  owner: development
